on: workflow_dispatch
name: Create App

jobs:
  create_app_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.2  
        
    - name: CreateApp
      uses: Microsoft/AL-GO/Actions/CreateApp@v5.0
      with:
        shell: pwsh
        type: PTE
        name: test
        publisher: Thomas Gortemaker
        idrange: 50000..51000
        project: '.github'
