on: workflow_dispatch
name: Create App

jobs:
  create_app_job:
    runs-on: ubuntu-latest

    steps:
    - name: Create App
      uses: .github/actions/CreateApp/action.yaml@v1
      with:
        type: PTE
        name: test
        publisher: Thomas Gortemaker
        idrange: 50000..51000
