# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Output logs
      run: |
        echo "This is a simple log."
        echo "GitHub Actions is running this workflow."
        echo "This workflow does not interact with the repository."
